[workspace]

members = [
    "arch",
    "devices",
    "global",
    "libhypatia",
    "memory",
    "monitor",
    "scheduler",
    "supervisor",
    "theon",
    "trace",
    "uart",
    "vcpu",
    "vm",
    "xtask",
]
